name: Add issue to bug tracker project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/ParadymHub/projects/1
          labeled: bug, needs-triage
          label-operator: OR
